export const ALL_USERS: Record<UserId, User> = {
  1: {
    id: 1,
    name: "Ting",
    avatar: "/avatar1.jpg",
    connections: [2, 5],
    status: "online",
    rank: 5,
    lastConnectionId: 2,
  },
  2: {
    id: 2,
    name: "Alex",
    avatar: "/avatar2.jpg",
    connections: [1, 3, 4],
    status: "offline",
    rank: 4,
    lastConnectionId: 3,
  },
  3: {
    id: 3,
    name: "Ceb",
    avatar: "/avatar3.jpg",
    connections: [2, 4],
    status: "busy",
    rank: 3,
    lastConnectionId: 4,
  },
  4: {
    id: 4,
    name: "Ami",
    avatar: "/avatar4.jpg",
    connections: [2, 3],
    status: "online",
    rank: 2,
    lastConnectionId: 3,
  },
  5: {
    id: 5,
    name: "Johan",
    avatar: "/avatar5.jpg",
    connections: [1],
    status: "busy",
    rank: 1,
    lastConnectionId: 1,
  },
};
